### ISSUE TITLE
This objective should be moved to ruby-objects-class-methods

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/ruby-objects-self#24] opened 2017-02-03 16:11 UTC
```diff
## Objectives

Developers should be able to:

 - Determine runtime context using `self`.
 - Invoke a getter or setter method using `self`.
- - Define and use class instance variables and class methods.
```

**Comment by jrhorn424** [comment] 2017-04-14 14:05
@ga-wdi-boston/core I'm closing this as duplicate of #23, especially since the title of this issue conflicts with the discussion over there. If I'm in error, feel free to re-open and add more context.

**Closed as completed by jrhorn424** 2017-04-14 14:05 UTC
Labels: duplicate
